export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

// config Driven UI
export const restaurantList = [
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "24204",
          name: "Domino's Pizza",
          uuid: "c47c9b16-8e3f-4453-80e9-775371ad90a5",
          city: "4",
          area: "Defence Colony",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "mn7bthsrm8f4kdorgw0q",
          cuisines: ["Pizzas"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          slaString: "30 MINS",
          lastMileTravel: 0,
          slugs: {
            restaurant: "dominos-pizza-near-moolchand-flyover-south-extension",
            city: "delhi",
          },
          cityState: "4",
          address:
            "A-1,Dda Shopping Complex,Near Moolchand Flyover,Defence Colony,New Delhi - 110024",
          locality: "Andrews Ganj",
          parentId: 2456,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3200,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3200,
            message: "",
            title: "Delivery Charge",
            amount: "3200",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          hasSurge: false,
          sla: {
            restaurantId: "24204",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            lastMileTravel: 0,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.4",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "456204",
          name: "Third Wave Coffee",
          uuid: "3a3f596e-1c00-4ee2-b553-e21ce00db3c0",
          city: "4",
          area: "Defence Colony",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "47a01e69717e471c15b1d830a7b7f713",
          cuisines: ["Beverages", "Snacks", "Desserts"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          slaString: "30 MINS",
          lastMileTravel: 4.5,
          slugs: {
            restaurant:
              "third-wave-coffee-roasters-south-extension-south-extension",
            city: "delhi",
          },
          cityState: "4",
          address:
            "Block D -19 , Ground Floor Defence Colony , DEFENCE COLONY, South East, Delhi, 110024",
          locality: "Lajpat Nagar",
          parentId: 274773,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "40% off",
            shortDescriptionList: [
              {
                meta: "40% off | Use GUILTFREE",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹100 | Use code GUILTFREE",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "40% OFF",
            shortDescriptionList: [
              {
                meta: "Use GUILTFREE",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "40% off up to ₹100 | Use code GUILTFREE",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5884222~p=4~eid=00000186-3fb4-bf8b-2e30-8f46004e046f",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "456204",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            lastMileTravel: 4.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.6",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "440231",
          name: "Matka peer Golden Biryani",
          uuid: "d54e01ec-2e6c-409a-b0e5-3ebe6314503b",
          city: "4",
          area: "Connaught Place",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "oyfz3chsvjcnxy7vrkcb",
          cuisines: ["Indian", "Biryani"],
          tags: [],
          costForTwo: 20000,
          costForTwoString: "₹200 FOR TWO",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          slaString: "29 MINS",
          lastMileTravel: 1.5,
          slugs: {
            restaurant: "matka-peer-golden-biryani-khan-market-khan-market",
            city: "delhi",
          },
          cityState: "4",
          address:
            "Shop no. 2 Dargah matka peer, near pragati maidan gate3, Mathura Rd, beside Bharat petroleum, Pragati Maidan, New Delhi, Delhi 110001, India",
          locality: "Mathura Road",
          parentId: 265401,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "440231",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            lastMileTravel: 1.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "385444",
          name: "Khan Chacha",
          uuid: "6ed03a63-3637-4b78-b1ea-aefaea2a934c",
          city: "4",
          area: "Khan Market",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "qclnpm4b3n8btjevl3dy",
          cuisines: ["Kebabs", "North Indian", "Mughlai"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          slaString: "30 MINS",
          lastMileTravel: 1.7999999523162842,
          slugs: {
            restaurant: "khan-chacha-khan-market-khan-market-2",
            city: "delhi",
          },
          cityState: "4",
          address:
            "Flat No-50, ( Ist & IInd Floor) Khan Market, New Delhi-110003, New Delhi (Delhi) - 110003",
          locality: "Middle Lane",
          parentId: 548,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "385444",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            lastMileTravel: 1.7999999523162842,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.4",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "152971",
          name: "KFC",
          uuid: "1c1af6d6-2076-4ffb-93bb-d6fae6a0d41c",
          city: "4",
          area: "Connaught Place",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
          cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          slaString: "34 MINS",
          lastMileTravel: 5.5,
          slugs: {
            restaurant: "kfc-connaught-place-connaught-place-2",
            city: "delhi",
          },
          cityState: "4",
          address:
            "KFC Restaurant, A12 Connaught Place, Inner Circle, Connaught Place 110001",
          locality: "A Block",
          parentId: 547,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=5932635~p=7~eid=00000186-3fb4-bf8b-2e30-8f47004e0778",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "152971",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            lastMileTravel: 5.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "314884",
          name: "Saz- American Brasserie",
          uuid: "75a452d6-aa2e-419d-b267-c86ab63138e0",
          city: "4",
          area: "Sundar Nagar",
          totalRatingsString: "Too Few Ratings",
          cloudinaryImageId: "yeq5dd68erjkdyjxv0q4",
          cuisines: ["American", "European", "Italian"],
          tags: [],
          costForTwo: 150000,
          costForTwoString: "₹1500 FOR TWO",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          slaString: "28 MINS",
          lastMileTravel: 1.2000000476837158,
          slugs: {
            restaurant: "saz--amercian-brasserie-khan-market-khan-market",
            city: "delhi",
          },
          cityState: "4",
          address:
            "21, First Floor, Behind HDFC Bank, Sunder Nagar Main Market, New Delhi -",
          locality: "Main Market",
          parentId: 387835,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.2 kms",
          hasSurge: false,
          sla: {
            restaurantId: "314884",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            lastMileTravel: 1.2000000476837158,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "--",
          totalRatings: 0,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
    {
      cardType: "restaurant",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "restaurant",
        data: {
          type: "F",
          id: "31754",
          name: "Gulati (Pandara Road)",
          uuid: "bbb488b4-3502-40ee-a10e-3ae33d2c721b",
          city: "4",
          area: "Pandara Market",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "al1itsrxkkrpbxjmkhno",
          cuisines: ["Indian"],
          tags: [],
          costForTwo: 100000,
          costForTwoString: "₹1000 FOR TWO",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          slaString: "34 MINS",
          lastMileTravel: 1.7999999523162842,
          slugs: {
            restaurant: "gulati-pandara-roaddelhi-khan-market",
            city: "delhi",
          },
          cityState: "4",
          address: "6, Pandara road market",
          locality: "Pandara Road Market",
          parentId: 16236,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
              {
                meta: "50% off | Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          aggregatedDiscountInfoV2: {
            header: "50% OFF",
            shortDescriptionList: [
              {
                meta: "Use WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            descriptionList: [
              {
                meta: "50% off up to ₹100 | Use code WELCOME50",
                discountType: "Percentage",
                operationType: "RESTAURANT",
              },
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: "",
          },
          chain: [],
          feeDetails: {
            fees: [],
            totalFees: 0,
            message: "",
            title: "",
            amount: "",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "31754",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            lastMileTravel: 1.7999999523162842,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      parentWidget: false,
    },
  ];
  